services:
  n8n:
  deploy:
  resources:
    limits:
      memory: 1GB
    image: n8nio/n8n:1.70.0
    restart: always
    ports:
      - "127.0.0.1:5678:5678"
    environment:
      - DB_TYPE=sqlite
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
    volumes:
      - ./n8n_data:/home/node/.n8n
    mem_limit: 1g
