services:
  # A PostgreSQL database on the free tier
  - type: pserv
    name: n8n-db
    plan: free
    postgres:
      version: 13

  # The n8n web service
  - type: web
    name: n8n
    plan: free # Use the free instance type
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_HOST
        fromService:
          type: pserv
          name: n8n-db
          property: host
      - key: DB_POSTGRESDB_PORT
        fromService:
          type: pserv
          name: n8n-db
          property: port
      - key: DB_POSTGRESDB_DATABASE
        fromService:
          type: pserv
          name: n8n-db
          property: database
      - key: DB_POSTGRESDB_USER
        fromService:
          type: pserv
          name: n8n-db
          property: user
      - key: DB_POSTGRESDB_PASSWORD
        fromService:
          type: pserv
          name: n8n-db
          property: password
      - key: WEBHOOK_URL
        fromService:
          type: web
          name: n8n
          property: url
