services:
  - type: pserv
    name: n8n-db
    plan: free
    # The following properties are specific to a postgres service
    properties:
      - property: postgres
        version: 13

  - type: web
    name: n8n
    plan: free
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_TYPE
        value: postgresdb
      - fromService:
          type: pserv
          name: n8n-db
          envVarKey: DB_POSTGRESDB_HOST
          property: host
      - fromService:
          type: pserv
          name: n8n-db
          envVarKey: DB_POSTGRESDB_PORT
          property: port
      - fromService:
          type: pserv
          name: n8n-db
          envVarKey: DB_POSTGRESDB_DATABASE
          property: database
      - fromService:
          type: pserv
          name: n8n-db
          envVarKey: DB_POSTGRESDB_USER
          property: user
      - fromService:
          type: pserv
          name: n8n-db
          envVarKey: DB_POSTGRESDB_PASSWORD
          property: password
      - fromService:
          type: web
          name: n8n
          envVarKey: WEBHOOK_URL
          property: url
