name: Docker Build Verification

on: [push]

jobs:
  build-video-renderer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build video-renderer Docker image
        run: |
          docker --version
          docker build ./video_renderer --file video_renderer/Dockerfile --tag video-renderer:$(date +%s)
